import Head from 'next/head'
import Image from 'next/image'
import Landing from '../components/Landing'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="py-10 px-16 lg:px-20">
      <Head>
        <title>stayHealthy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo 1.png" />
      </Head>

      <main className="flex flex-col items-center">
        <Navbar />
        <div className="max-w-7xl md:w-xl lg:w-5xl">
    
        </div>
        <Landing/>
      </main>
      
    </div>
  )
}
